import type { Metadata } from "next";
import localFont from "next/font/local";
import { inter } from "./fonts/font";
import Header from "./Header";
import { CartProvider } from "./_components/context/cart";
import "./globals.css";
import Footer from "./Footer";
import NextAuthProvider from "./provider/NextAuthProvider";
import { WishlistProvider } from "./_components/context/wishlist";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${inter.className} ${geistMono.variable} antialiased`}
      >
        {" "}
        <CartProvider>
          <WishlistProvider>
            <NextAuthProvider>
              <Header />
              {children}
              <Footer />
            </NextAuthProvider>
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
